config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :comments
  root to: 'comments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :strengths, presence: true
  validates :weaknesses, presence: true
  validates :message, presence: true
  belongs_to :user
  validates :hobby, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum:6 }
  validates :name, presence: true
  has_many :comments
end
      

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:name])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'monmon' && password == '2222'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @users = User.all 
    @comments = Comment.all
    @current_user = current_user
    @user = User.new
    @comment = Comment.new
  end

  def new
    @user = User.new
    @comment = Comment.new
  end
  def create   
    @comment = Comment.new(comment_params)
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to comments_path
    else
      render :new, status: :unprocessable_entity
   end
  end
  def edit
    @comment = Comment.find(params[:id])
  end
  def show
    @comment = Comment.find(params[:id])
    @user = @comment.user
  end
  def update
    if 
      @comment = Comment.find(params[:id])
      @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:birthdate, :strengths, :weaknesses, :image, :message, :hobby).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
 def same_user?(current_user, user)
      current_user.id == user.id
    
  end
end

app/views/comments/edit.html.erb
<%= form_with model: @comment, url: comment_path(@comment), method: :patch, id: 'charge-form', class: 'transaction-form-wrap', data: { turbo: false }, local: true do |f| %>
      <div class="introduce">
        <div class="introduce-right">
          <!-- 写真もしくは画像を入力 -->
          <span class="indispensable">(必須)</span>
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id: "comment-image" %>
        </div>
        <div class="introduce-main">

            <label class="form-text">強み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :strengths, placeholder: "Strengths", class: "strengths-form" %>

            <label class="form-text">弱み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :weaknesses, placeholder: "Weaknesses", class: "weaknesses-form" %>

            <label class="form-text">生年月日</label>
            <span class="indispensable">(必須)</span>
            <div class='input-birth-wrap'>
            <%= raw sprintf(
              f.date_select(
                    :birthdate,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
            </div>

            <label class="form-text">メッセージ</label>
              <%= f.text_area :message, placeholder: "MESSAGE", class: "message-form" %>
            </div>
              <%= f.submit "SEND", class: "send" %>
        
         </div>
       <% end %>

app/views/comments/index.html.erb
<%= form_with model: @comment, url: comments_path, id: 'charge-form', class: 'transaction-form-wrap', data: { turbo: false }, local: true do |f| %>
  <table class="detail-table">
    <tbody>
      <% @users.each do |user| %>
        <% if user_signed_in? && same_user?(current_user, user) %>
          <tr>
            <th class="detail-user">名前</th>
            <td class="detail-value"><%= user.name %></td>
          </tr>
          <tr>
            <th class="detail-user">ニックネーム</th>
            <td class="detail-value"><%= user.nickname %></td>
          </tr>

          <!-- コメントループをユーザーループの内側に移動 -->
          <% @comments.each do |comment| %>
            <!-- 現在のユーザーに関連するコメントを表示 -->
            <% if comment.user_id == user.id %>
              <tr>
                <th class="detail-user">生年月日</th>
                <td class="detail-value"><%= comment.birthdate %></td>
              </tr>
              <tr>
                <th class="detail-user">強み</th>
                <td class="detail-value"><%= comment.strengths %></td>
              </tr>
              <tr>
                <th class="detail-user">弱み</th>
                <td class="detail-value"><%= comment.weaknesses %></td>
              </tr>
              <tr>
                <th class="detail-user">メッセージ</th>
                <td class="detail-value"><%= comment.message %></td>
              </tr>
              <tr>
                <th class="detail-user">趣味</th>
                <td class="detail-value"><%= comment.hobby %></td>
              </tr>
              
              <!-- 画像のコードもコメントループの内側に移動 -->
              <div class='user-photo-info'>
                <% if comment.image.attached? %>
                  <%= link_to comment_path(comment) do %>
                  <%= image_tag comment.image, class: 'user-photo-img' %>
                  <% end %>
                <% else %>
                  <%= image_tag 'test_image.jpg.jpg', class: 'user-photo-img', alt: 'デフォルト画像' %>
                <% end %>
              </div>
              
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: comments_path, method: :post, id: 'charge-form', class: 'transaction-form-wrap', data: { turbo: false }, local: true do |f| %>
      <div class="introduce">
        <div class="introduce-right">
          <!-- 写真もしくは画像を入力 -->
          <span class="indispensable">(必須)</span>
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id: "comment-image" %>
        </div>
        <div class="introduce-main">

            <label class="form-text">強み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :strengths, placeholder: "Strengths", class: "strengths-form" %>

            <label class="form-text">弱み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :weaknesses, placeholder: "Weaknesses", class: "weaknesses-form" %>

            <label class="form-text">趣味</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :hobby, placeholder: "hobby", class: "hobby-form" %>

            <label class="form-text">生年月日</label>
            <span class="indispensable">(必須)</span>
            <div class='input-birth-wrap'>
            <%= raw sprintf(
              f.date_select(
                    :birthdate,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
            </div>

            <label class="form-text">メッセージ</label>
              <%= f.text_area :message, placeholder: "MESSAGE", class: "message-form" %>
            </div>
              <%= f.submit "SEND", class: "send" %>
        
         </div>
       <% end %>

app/views/comments/show.html.erb
<div class='transaction-form-wrap'> 
    <table class="detail-table">
      <tbody>
      <% if @comment.present? %>
        <tr>
          <th class="detail-user">生年月日</th>
          <td class="detail-value"><%= @comment.birthdate %></td>
        </tr>
        <tr>
          <th class="detail-user">強み</th>
          <td class="detail-value"><%= @comment.strengths %></td>
        </tr>
        <tr>
          <th class="detail-user">弱み</th>
          <td class="detail-value"><%= @comment.weaknesses %></td>
        </tr>
        <tr>
          <th class="detail-user">メッセージ</th>
          <td class="detail-value"><%= @comment.message %></td>
        </tr>
      <% end %>
     </tbody>
    </table>

    <div class='user-photo-info'>
        <%= image_tag @comment.image, class: 'user-photo-img' %>
    </div>
    <div class='comment_btn'>
      <% if user_signed_in? %> 
          <%= link_to "編集",edit_comment_path(@comment.id), method: :get, class: "comment-red-btn" %>
          <p class="or-text">or</p>
          <%= link_to "削除", comment_path(@comment.id), data: { turbo_method: :delete }, class:"comment-destroy" %>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroduceSecondApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row"> 
        <h1 class="grid-6"><a>introduce_second_app</a></h1>
        <div class="user_nav grid-6">
         <ul class='lists-right'>
         <% if user_signed_in? %>
           <li><%= link_to '作成する', new_comment_path, class: "introduce-user" %></li>
           <li><%= link_to current_user.nickname, comments_path, class: "user-nickname" %></li>
           <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout" %></li>
         <% else %>
           <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
           <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
         <% end %>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright introduce_second_app 2024.
      </p>
    </footer>
  </body>
</html>

app/views/users/-error_message.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/-error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<%= form_with model: @user, url: users_path, id: 'charge-form', class: 'transaction-form-wrap', data: { turbo: false }, local: true do |f| %>
  <table class="detail-table">
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th class="detail-user">名前</th>
          <td class="detail-value"><%= user.name %></td>
        </tr>
        <tr>
          <th class="detail-user">ニックネーム</th>
          <td class="detail-value"><%= user.nickname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% @comments.each do |comment| %>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-user">生年月日</th>
          <td class="detail-value"><%= comment.birthdate %></td>
        </tr>
        <tr>
          <th class="detail-user">強み</th>
          <td class="detail-value"><%= comment.strengths %></td>
        </tr>
        <tr>
          <th class="detail-user">弱み</th>
          <td class="detail-value"><%= comment.weaknesses %></td>
        </tr>
        <tr>
          <th class="detail-user">メッセージ</th>
          <td class="detail-value"><%= comment.message %></td>
        </tr>
      </tbody>
    </table>

    <div class='user-photo-info'>
      <% if @comment.image.attached? %>
        <%= image_tag @comment.image, class: 'user-photo-img' %>
      <% else %>
        <%= image_tag 'test_image.jpg.jpg', class: 'user-photo-img', alt: 'Default Image' %>
      <% end %>
    </div>
  <% end %>
<% end %> 

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path, method: :post, id: 'charge-form', class: 'transaction-form-wrap', data: { turbo: false }, local: true do |f| %>
      <div class="introduce">
        <div class="introduce-right">
          <!-- 写真もしくは画像を入力 -->
          <span class="indispensable">(必須)</span>
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id: "comment-image" %>
        </div>
        <div class="introduce-main">

            <label class="form-text">強み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :strengths, placeholder: "Strengths", class: "strengths-form" %>

            <label class="form-text">弱み</label>
            <span class="indispensable">(必須)</span>
            <%= f.text_field :weaknesses, placeholder: "Weaknesses", class: "weaknesses-form" %>

            <label class="form-text">生年月日</label>
            <span class="indispensable">(必須)</span>
            <div class='input-birth-wrap'>
            <%= raw sprintf(
              f.date_select(
                    :birthdate,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
            </div>

            <label class="form-text">メッセージ</label>
              <%= f.text_area :message, placeholder: "MESSAGE", class: "message-form" %>
            </div>
              <%= f.submit "SEND", class: "send" %>
        
         </div>
       <% end %>